# -*- coding: utf-8 -*-
"""API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k6IovgABGkXsPXoV6nQvKPvpUZOgoosd
"""

from google.colab import drive
drive.mount('/content/drive')

from google.colab import files
uploaded = files.upload()

import pickle as pkl
with open('/content/Linear_Regression_model.pkl', 'rb') as file:
    model_file = pkl.load(file)

import numpy as np
def pred_output(user_input):
    model_input = np.array(user_input).reshape(-1, 6)
    output = model_file.predict(model_input)
    return output[0]

def main():
    age = input("Enter your age: ")
    sex = input("Enter you sex(M/F): ")
    if sex =='F':
      sex = 0
    else:
      sex = 1
    bmi = input("Enter your bmi: ")
    children = input("Enter number of your children: ")
    smoker = input("Do you smoke(yes/no)? ")
    if smoker == 'yes':
      smoker = 1
    else:
      smoker = 0
    region = input("Enter your region: ")
    if region=='southwest':
      region=0
    elif region=='northwest':
      region=1
    elif region=='southeast':
      region=2
    else:
      region=3

    #Predicting result
    user_input = [age, sex, bmi, children, smoker, region]
    user_input = list(map(float, user_input))
    prediction = pred_output(user_input)
    return prediction



prediction = main()

#Displaying prediction
print("Expected Charges: ${:.2f}".format(prediction))